name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - name: ESLint
        run: pnpm run lint

      - name: Stylelint
        run: pnpm run lint:styles

      - name: Prettier check
        run: pnpm run format:check

      - name: Tests
        run: pnpm run test

      - name: Build
        run: pnpm run build
        env:
          API_BASE_URL: https://prueba-tecnica-api-tienda-moviles.onrender.com
          API_KEY: ${{ secrets.API_KEY_CI }}
